<a href="https://colab.research.google.com/github/NavyaBiju/CNN-CLASSIFIER/blob/main/mohmam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import cv2 as cv
import random
import os
import matplotlib.pyplot as plt
import pickle
%matplotlib inline

In [ ]:
DIRECTORY = r'/content/drive/MyDrive/dataset'
# a raw string(r'...') is used to treat backslash(\) as a normal character
CATEGORIES = ['mammooty','mohanlal']

In [ ]:
IMG_SIZE = 224

data = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        label = CATEGORIES.index(category)
        img_arr = cv.imread(img_path, cv.IMREAD_GRAYSCALE)
        img_arr = cv.resize(img_arr,(IMG_SIZE,IMG_SIZE))
        data.append([img_arr,label])
#         labelling the data


In [ ]:
random.shuffle(data)
# to shuffle the data

In [ ]:
X = []
y = []

for features, labels in data:
    X.append(features)
    y.append(labels)

In [ ]:
X = np.array(X)
y = np.array(y)
# changed X & y into arrays and stored it in respective variables

In [ ]:
X

array([[[ 17,  18,  20, ...,  11,  11,  11],
        [ 21,  23,  25, ...,  10,   9,   9],
        [ 27,  29,  31, ...,   9,   8,   8],
        ...,
        [ 48,  52,  57, ...,  17,  17,  17],
        [ 48,  53,  57, ...,  17,  17,  17],
        [ 48,  52,  57, ...,  17,  17,  17]],

       [[ 20,  21,  22, ...,  27,  25,  24],
        [ 20,  21,  22, ...,  27,  25,  24],
        [ 20,  21,  22, ...,  26,  26,  26],
        ...,
        [ 57,  56,  55, ...,  62,  62,  62],
        [ 51,  52,  55, ...,  62,  62,  62],
        [ 48,  50,  55, ...,  62,  62,  62]],

       [[  1,   5,  11, ...,   4,  11,  15],
        [  1,   4,   9, ...,   4,  11,  15],
        [  1,   3,   7, ...,   3,  12,  17],
        ...,
        [ 79,  80,  81, ...,   8,  15,  19],
        [ 72,  73,  75, ...,  14,  46,  64],
        [ 68,  69,  71, ...,  18,  64,  91]],

       ...,

       [[216, 215, 205, ...,   7,   6,   6],
        [216, 215, 205, ...,   8,   6,   6],
        [215, 214, 207, ...,   7,   4,   4

In [ ]:
y

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,

In [ ]:
X = pickle.dump(X,open('X.pkl', 'wb'))
y = pickle.dump(y,open('y.pkl', 'wb'))

# storing the data in a pickle file

In [ ]:
import pickle


In [ ]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [ ]:
X

array([[[ 17,  18,  20, ...,  11,  11,  11],
        [ 21,  23,  25, ...,  10,   9,   9],
        [ 27,  29,  31, ...,   9,   8,   8],
        ...,
        [ 48,  52,  57, ...,  17,  17,  17],
        [ 48,  53,  57, ...,  17,  17,  17],
        [ 48,  52,  57, ...,  17,  17,  17]],

       [[ 20,  21,  22, ...,  27,  25,  24],
        [ 20,  21,  22, ...,  27,  25,  24],
        [ 20,  21,  22, ...,  26,  26,  26],
        ...,
        [ 57,  56,  55, ...,  62,  62,  62],
        [ 51,  52,  55, ...,  62,  62,  62],
        [ 48,  50,  55, ...,  62,  62,  62]],

       [[  1,   5,  11, ...,   4,  11,  15],
        [  1,   4,   9, ...,   4,  11,  15],
        [  1,   3,   7, ...,   3,  12,  17],
        ...,
        [ 79,  80,  81, ...,   8,  15,  19],
        [ 72,  73,  75, ...,  14,  46,  64],
        [ 68,  69,  71, ...,  18,  64,  91]],

       ...,

       [[216, 215, 205, ...,   7,   6,   6],
        [216, 215, 205, ...,   8,   6,   6],
        [215, 214, 207, ...,   7,   4,   4

In [ ]:
y

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,

In [ ]:
X = X/255

In [ ]:
X

array([[[0.06666667, 0.07058824, 0.07843137, ..., 0.04313725,
         0.04313725, 0.04313725],
        [0.08235294, 0.09019608, 0.09803922, ..., 0.03921569,
         0.03529412, 0.03529412],
        [0.10588235, 0.11372549, 0.12156863, ..., 0.03529412,
         0.03137255, 0.03137255],
        ...,
        [0.18823529, 0.20392157, 0.22352941, ..., 0.06666667,
         0.06666667, 0.06666667],
        [0.18823529, 0.20784314, 0.22352941, ..., 0.06666667,
         0.06666667, 0.06666667],
        [0.18823529, 0.20392157, 0.22352941, ..., 0.06666667,
         0.06666667, 0.06666667]],

       [[0.07843137, 0.08235294, 0.08627451, ..., 0.10588235,
         0.09803922, 0.09411765],
        [0.07843137, 0.08235294, 0.08627451, ..., 0.10588235,
         0.09803922, 0.09411765],
        [0.07843137, 0.08235294, 0.08627451, ..., 0.10196078,
         0.10196078, 0.10196078],
        ...,
        [0.22352941, 0.21960784, 0.21568627, ..., 0.24313725,
         0.24313725, 0.24313725],
        [0.2

In [ ]:
X.shape

(994, 224, 224)

In [ ]:
X = X.reshape(-1, 224, 224, 1)

In [ ]:
X.shape

(994, 224, 224, 1)

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [ ]:
model = Sequential()

In [ ]:
# Step 1 - Convolution
model.add(Conv2D(64,(3,3), activation='relu'))
# Step 2 - Pooling
model.add(MaxPooling2D((2,2)))

# Adding a second convolutional layer
model.add(Conv2D(64,(3,3), activation='relu'))
model.add(MaxPooling2D((2,2)))

# Step 3 - Flattening
model.add(Flatten())

# Step 4 - Full Connection
model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

# Step 5 - Output Layer
model.add(Dense(2, activation= 'sigmoid'))

In [ ]:
model.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
model.fit(X, y, epochs=10, validation_split=0.2)

Epoch 1/10
25/25 [==============================] - 142s 6s/step - loss: 1.2468 - accuracy: 0.6541 - val_loss: 0.5894 - val_accuracy: 0.7387
Epoch 2/10
25/25 [==============================] - 136s 5s/step - loss: 0.4433 - accuracy: 0.7774 - val_loss: 0.3155 - val_accuracy: 0.8593
Epoch 3/10
25/25 [==============================] - 139s 6s/step - loss: 0.2131 - accuracy: 0.9195 - val_loss: 0.4303 - val_accuracy: 0.8191
Epoch 4/10
25/25 [==============================] - 136s 5s/step - loss: 0.1354 - accuracy: 0.9472 - val_loss: 0.1827 - val_accuracy: 0.9447
Epoch 5/10
25/25 [==============================] - 136s 5s/step - loss: 0.0414 - accuracy: 0.9874 - val_loss: 0.1496 - val_accuracy: 0.9749
Epoch 6/10
25/25 [==============================] - 135s 5s/step - loss: 0.0190 - accuracy: 0.9975 - val_loss: 0.1893 - val_accuracy: 0.9548
Epoch 7/10
25/25 [==============================] - 136s 5s/step - loss: 0.0143 - accuracy: 0.9962 - val_loss: 0.1865 - val_accuracy: 0.9548
Epoch 8/10
25

In [ ]:
scores = model.evaluate(X,y,verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 99.20%


In [ ]:
X.shape

(994, 224, 224, 1)

In [ ]:
model.save('cnn4.model',save_format='h5')

In [ ]:
import numpy as np
import cv2
import keras

In [ ]:
CATEGORIES = ['mammooty', 'mohanlal']


def image(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    new_arr = cv2.resize(img, (224, 224))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 224,224, 1)
    return new_arr
#preprocessing the user input

In [ ]:
model = keras.models.load_model('cnn4.model')

In [ ]:
result = model.predict([image('/content/drive/MyDrive/dataset/mammooty/mammooty64.png')])
if result[0][0] == 1:
    prediction = 'mamooty'
elif result[0][0] == 0:
    prediction = 'mohanlal'
else:
    prediction = 'I dont know this guy!'
print(prediction)

1/1 [==============================] - 0s 245ms/step
mamooty
